// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqa-CgK1RYSnDgXCx0FrRHKOa41a5KrzY',
    appId: '1:615905251954:web:0129768be3877438dc68eb',
    messagingSenderId: '615905251954',
    projectId: 'superbai-81bc6',
    authDomain: 'superbai-81bc6.firebaseapp.com',
    storageBucket: 'superbai-81bc6.appspot.com',
    measurementId: 'G-60EWT9P349',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJxWqMd7HfPpvki9TlbjajvLOpp8wGm0w',
    appId: '1:615905251954:android:6c93961f0ad345dbdc68eb',
    messagingSenderId: '615905251954',
    projectId: 'superbai-81bc6',
    storageBucket: 'superbai-81bc6.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGFc09W5GnkqmtvLDUEwlA5X0hrMMFKs',
    appId: '1:615905251954:ios:8d72eb7edb3a99e9dc68eb',
    messagingSenderId: '615905251954',
    projectId: 'superbai-81bc6',
    storageBucket: 'superbai-81bc6.appspot.com',
    iosBundleId: 'com.superbai.sujal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgGFc09W5GnkqmtvLDUEwlA5X0hrMMFKs',
    appId: '1:615905251954:ios:8d72eb7edb3a99e9dc68eb',
    messagingSenderId: '615905251954',
    projectId: 'superbai-81bc6',
    storageBucket: 'superbai-81bc6.appspot.com',
    iosBundleId: 'com.superbai.sujal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqa-CgK1RYSnDgXCx0FrRHKOa41a5KrzY',
    appId: '1:615905251954:web:f17089b475397b53dc68eb',
    messagingSenderId: '615905251954',
    projectId: 'superbai-81bc6',
    authDomain: 'superbai-81bc6.firebaseapp.com',
    storageBucket: 'superbai-81bc6.appspot.com',
    measurementId: 'G-JTE2CZZ322',
  );
}
